# branchName: short
branchName: '${issue.number}'

branches:
  - label: enhancement
    prefix: feature-
  - label: bug
    prefix: issue-
  - label: '*'
    prefix: issue-

commentMessage: 'Branch `${branchName}` created for issue: "${issue.title}"'
