# branchName: short
branchName: '${issue.number}'

branches:
  - label: enhancement
    prefix: feature-
  - label: channel
    prefix: channel-
  - label: bug
    prefix: bug-
  - label: '*'
    prefix: issue-

commentMessage: | 
  'Branch `${branchName}` was created for issue: "${issue.title}"
  
  * Url: ${repository.html_url}/tree/${branchName}
  * Kodi Zip: ${repository.html_url}/archive/refs/heads/${branchName}.zip'
